fun main() {
    // Write some code to cause an exception
    val array = arrayOf("3","4","5")
    println(array[4])
}